# Generated by Django 5.0.7 on 2024-08-10 13:15

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsearch', '0001_addpgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('vector_product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('productDes', models.TextField(max_length=5000)),
                ('image', models.URLField(max_length=2048)),
                ('price', models.FloatField()),
                ('sold_units', models.IntegerField()),
                ('rating', models.FloatField()),
                ('no_review', models.IntegerField()),
                ('link', models.URLField(max_length=2048)),
                ('shipmentOrigin', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestProducts',
            fields=[
                ('productID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('productDesc', models.TextField(max_length=5000)),
                ('productLink', models.URLField(max_length=2048)),
                ('productPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NameEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_name', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsearch.product')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_name'], m=16, name='pname_index', opclasses=['vector_l2_ops'])],
            },
        ),
        migrations.CreateModel(
            name='DescEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_desc', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('document', models.CharField(blank=True, max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsearch.product')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_desc'], m=16, name='pdesc_index', opclasses=['vector_l2_ops'])],
            },
        ),
        migrations.CreateModel(
            name='TestEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_name', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_desc', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsearch.testproducts')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_desc'], m=16, name='desc_index', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
