# Generated by Django 5.0.7 on 2024-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsearch', '0001_addpgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProducts',
            fields=[
                ('productID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('productDesc', models.TextField(max_length=5000)),
                ('productLink', models.URLField(max_length=2048)),
                ('productPrice', models.FloatField()),
            ],
        ),
    ]
