# Generated by Django 5.0.7 on 2024-07-25 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsearch', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproducts',
            name='productID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
