# Generated by Django 5.0.7 on 2024-07-26 09:23

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsearch', '0003_alter_testproducts_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_name', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_desc', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsearch.testproducts')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_desc'], m=16, name='desc_index', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
