# Generated by Django 5.0.7 on 2024-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsearch', '0005_product_nameembeddings_descembeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='descembeddings',
            name='document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
